In [1]:
import pandas as pd
import datetime
import sqlite3
import pymysql
import pandas.io.sql as psql
from datetime import datetime as dt
import numpy as np
import pandas.tseries.offsets as offsets
import sqlalchemy as sqa
import matplotlib.pyplot as plt
import python_ss as ps
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json

import os
import ast
import db_dtypes
from google.cloud import bigquery
from google.oauth2 import service_account
from google.cloud import secretmanager

In [2]:
def access_secret_version(project_id, secret_id, version_id='latest'):
    client = secretmanager.SecretManagerServiceClient()

    name = f"projects/{project_id}/secrets/{secret_id}/versions/{version_id}"
    response = client.access_secret_version(request={"name": name})
    payload = response.payload.data.decode("UTF-8")
    return ast.literal_eval(payload)

In [3]:
# 上記関数を実行するコードが記載されています。こちらもそのままお使いください。
credentials = service_account.Credentials.from_service_account_info(
access_secret_version('temp-for-sandbox', 'TEMP_CREDENTIAL_KEY'),
scopes=["https://www.googleapis.com/auth/cloud-platform"],)

C:\Users\suehara\Anaconda3\lib\site-packages\google\auth\_default.py:78: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

In [4]:
dt_now = datetime.datetime.now()
dt_now = dt_now.strftime('%Y%m%d')
dt_now

'20230531'

In [5]:
##extitle + dt_now + ".xlsx"
path1 = "//172.16.0.232/CoffeeCrazy/経営ソリューション事業部/□スカウト推進部□/060 ※社外秘※共通シート/アンタッチャブルリスト/"
extitle = "【発注用】アンタッチャ一覧"
extitle = extitle + dt_now + ".xlsx"
extitle = path1 + extitle
extitle

'//172.16.0.232/CoffeeCrazy/経営ソリューション事業部/□スカウト推進部□/060 ※社外秘※共通シート/アンタッチャブルリスト/【発注用】アンタッチャ一覧20230531.xlsx'

In [6]:
df = pd.read_excel(extitle, sheet_name = 'アンタッチャ一覧',usecols=[3,6,14,16])

In [26]:
untouch = df.copy()

In [27]:
untouch

,CompanyName,JobName,BossName,Note
0,CELVINVIETNAMCOMPANYLIMITED.,NaN,NaN,2012/04/18アンタッチャ。依頼：市場開発部。株式会社ｾﾙｳﾞｧﾝの関連会社。期間：最...
1,株式会社ｻｰｸﾙ,不動産,NaN,988116552とは別会社 アンタッチャ担当：藤田 依頼：スカウト推進部
2,東武ｴｽﾃｰﾄ,NaN,NaN,期間：無制限? クライアント
3,株式会社ｵｰｼﾞｯｸ(ｵｰｼﾞｯｸｸﾞﾙｰﾌﾟ),動力伝導装置製造,田中 文彦,21/5/7ｱﾝﾀ。依頼：市開。期間：最終入金から1年間。20/7/28ｱﾝﾀ。依頼：顧問名...
4,株式会社ﾋﾞｰｽﾞｸﾘｴｲﾃｨﾌﾞｽﾞ,広告代理業,NaN,07/7/26アンタッチャ 依頼：市場開発 株式会社ﾋﾞｰｽﾞｲﾝﾀｰﾅｼｮﾅﾙの関連会社
...,...,...,...,...
26033,株式会社ﾊﾛ,ソフト受託開発,矢野 卓,2021/02/12アンタッチャ。依頼：顧問名鑑事業部。期間：最終入金から1年間。2012/...
26034,株式会社ﾎﾜｲﾄﾋﾞｼﾞﾈｽｲﾆｼｱﾃｨﾌﾞ,産業用電気機器卸,谷井 剛,2013/06/20アンタッチャ。依頼：市場開発部。株式会社ﾌｫｰﾊﾞﾙの関連会社。期間：最...
26035,株式会社ﾊﾟﾜｰﾌｨﾅﾝｼｬﾙｸﾞﾙｰﾌﾟ,NaN,NaN,2010/03/09アンタッチャ。依頼：市場開発部。株式会社ﾊﾟﾜｰｺﾝｻﾙﾃｨﾝｸﾞﾈｯﾄ...
26036,ﾊﾟﾅﾌｰｽﾞ株式会社,他の水産食料品製造,NaN,2021/10/14 倒産。 https://n-seikei.jp/2021/07/pos...
26037,ﾘｿﾞｰﾄ開発ﾌﾟﾛｼﾞｪｸﾄ,-,NaN,※特殊案件【0011118】のクライアントコードとして登録※（2017.5.31）

In [29]:
path2 = "//172.16.0.232/CoffeeCrazy3/新規事業室（藤社長）/転機_候補者対応関連/登録者エクセル格納フォルダ/相馬/アンタッチャ一覧.xlsx"
untouch.to_excel(path2,sheet_name = 'アンタッチャ一覧',index=False)
path2

'//172.16.0.232/CoffeeCrazy3/新規事業室（藤社長）/転機_候補者対応関連/登録者エクセル格納フォルダ/相馬/アンタッチャ一覧.xlsx'

In [30]:
tenki_candidate_query = """
SELECT
id as tenki_ID,
concat(replace(shi," ",""),replace(mei," ","")) as name,
replace(replace(replace(comp_name," ",""),"　",""),"・","") as CompanyName
FROM `temp-380708.live_tenki.user_info`
where replace(shi," ","") != ""
AND replace(mei," ","") != ""
AND id >= 49915 
order by id
"""
##created_at >= CURRENT_DATE('Asia/Tokyo')-10

client = bigquery.Client(credentials=credentials, project=credentials.project_id)
tenki_candidate = client.query(tenki_candidate_query).result().to_dataframe()

In [31]:
tenki_candidate

       tenki_ID  name        CompanyName
0         49916  宮島信文         株式会社ジーテイスト
1         49917  藤川卓也       クレディスイス証券•銀行
2         49918  南部正明      NoveWorks株式会社
3         49919   小野満           中日販売株式会社
4         49920  富田輝明            株式会社清光社
...         ...   ...                ...
44443    105337  髙橋一晃         株式会社TBSテレビ
44444    105338  向井昌博  ネクスティシステムデザイン株式会社
44445    105340  成山光史           株式会社フェース
44446    105341   森勝彦        株式会社Ｇファクトリー
44447    105342  両角真樹         株式会社ディルバート

[44448 rows x 3 columns]

In [32]:
untouch

,CompanyName,JobName,BossName,Note
0,CELVINVIETNAMCOMPANYLIMITED.,NaN,NaN,2012/04/18アンタッチャ。依頼：市場開発部。株式会社ｾﾙｳﾞｧﾝの関連会社。期間：最...
1,株式会社ｻｰｸﾙ,不動産,NaN,988116552とは別会社 アンタッチャ担当：藤田 依頼：スカウト推進部
2,東武ｴｽﾃｰﾄ,NaN,NaN,期間：無制限? クライアント
3,株式会社ｵｰｼﾞｯｸ(ｵｰｼﾞｯｸｸﾞﾙｰﾌﾟ),動力伝導装置製造,田中 文彦,21/5/7ｱﾝﾀ。依頼：市開。期間：最終入金から1年間。20/7/28ｱﾝﾀ。依頼：顧問名...
4,株式会社ﾋﾞｰｽﾞｸﾘｴｲﾃｨﾌﾞｽﾞ,広告代理業,NaN,07/7/26アンタッチャ 依頼：市場開発 株式会社ﾋﾞｰｽﾞｲﾝﾀｰﾅｼｮﾅﾙの関連会社
...,...,...,...,...
26033,株式会社ﾊﾛ,ソフト受託開発,矢野 卓,2021/02/12アンタッチャ。依頼：顧問名鑑事業部。期間：最終入金から1年間。2012/...
26034,株式会社ﾎﾜｲﾄﾋﾞｼﾞﾈｽｲﾆｼｱﾃｨﾌﾞ,産業用電気機器卸,谷井 剛,2013/06/20アンタッチャ。依頼：市場開発部。株式会社ﾌｫｰﾊﾞﾙの関連会社。期間：最...
26035,株式会社ﾊﾟﾜｰﾌｨﾅﾝｼｬﾙｸﾞﾙｰﾌﾟ,NaN,NaN,2010/03/09アンタッチャ。依頼：市場開発部。株式会社ﾊﾟﾜｰｺﾝｻﾙﾃｨﾝｸﾞﾈｯﾄ...
26036,ﾊﾟﾅﾌｰｽﾞ株式会社,他の水産食料品製造,NaN,2021/10/14 倒産。 https://n-seikei.jp/2021/07/pos...
26037,ﾘｿﾞｰﾄ開発ﾌﾟﾛｼﾞｪｸﾄ,-,NaN,※特殊案件【0011118】のクライアントコードとして登録※（2017.5.31）

In [33]:
# In[5]:

untauch = untouch
untauch['CompanyName'] = untauch['CompanyName'].replace(" ","").replace("　","").replace("・","")
untauch = untauch[['CompanyName']]
untauch_list = untauch['CompanyName'].tolist()
untauch

                        CompanyName
0      CELVINVIETNAMCOMPANYLIMITED.
1                          株式会社ｻｰｸﾙ
2                           東武ｴｽﾃｰﾄ
3          株式会社ｵｰｼﾞｯｸ(ｵｰｼﾞｯｸｸﾞﾙｰﾌﾟ)
4               株式会社ﾋﾞｰｽﾞｸﾘｴｲﾃｨﾌﾞｽﾞ
...                             ...
26033                        株式会社ﾊﾛ
26034        株式会社ﾎﾜｲﾄﾋﾞｼﾞﾈｽｲﾆｼｱﾃｨﾌﾞ
26035         株式会社ﾊﾟﾜｰﾌｨﾅﾝｼｬﾙｸﾞﾙｰﾌﾟ
26036                   ﾊﾟﾅﾌｰｽﾞ株式会社
26037               ﾘｿﾞｰﾄ開発ﾌﾟﾛｼﾞｪｸﾄ

[26038 rows x 1 columns]

In [34]:
import pandas as pd
import pymysql
import jaconv
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

In [35]:
def get_untauch(x):
    count = 0
    for i in untauch_list:
        if x in i:
            count += 1
    if count > 0:
        return '現S同意書回収'
    else:
        return None

def remove_kabu(x):
    remove_dict = {"株式会社": "", "（株）": "", "(株)": "", "㈱": "",
                   "有限会社": "", "（有）": "", "(有)": "",
                  }
    if type(x) is pd.core.series.Series:
        x = x.replace(remove_dict, regex=True)
    else:
        x = x.rename(index=remove_dict, regex=True)
    return x

In [36]:
# In[6]:
tenki_candidate['CompanyName'] = tenki_candidate['CompanyName'].apply(lambda x: jaconv.z2h(x))

In [37]:
tenki_candidate['変換CompanyName'] = remove_kabu(tenki_candidate['CompanyName'])

In [38]:
tenki_candidate['アンタッチャ'] = tenki_candidate['変換CompanyName'].apply(lambda x: get_untauch(x))

In [39]:
tenki_candidate = tenki_candidate.dropna(subset={'アンタッチャ'})

In [40]:
tenki_candidate = tenki_candidate[['tenki_ID','アンタッチャ','変換CompanyName']]

In [41]:
tenki_candidate

       tenki_ID   アンタッチャ 変換CompanyName
10        49926  現S同意書回収      歯愛ﾒﾃﾞｨｶﾙ
13        49929  現S同意書回収         LIXIL
14        49930  現S同意書回収            なし
15        49931  現S同意書回収            大京
17        49933  現S同意書回収       ﾊﾟﾅｿﾆｯｸ
...         ...      ...           ...
44435    105329  現S同意書回収          日本電気
44440    105334  現S同意書回収          TOTO
44441    105335  現S同意書回収        ｵｰｼﾞｯｸ
44442    105336  現S同意書回収          ﾎﾟｰﾗ
44445    105340  現S同意書回収          ﾌｪｰｽ

[9029 rows x 3 columns]

In [42]:
#マスタの最後のIDと行番号を取得する
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
json_path = r"C:\Users\suehara\Desktop\お転機BOX\ぱいそん練習\python_ss\credentials.json"
service = ps.get_auth(SCOPES,json_path)
SPREADSHEET_ID = '15qRR-yfJxgCh_TpXwBjBHNAnc8yAeTUCF0-Y_N6GoIo'
Sheet_NAME = '現Sチェック!A'
Sheet_row = ":A"
RANGE_NAME = Sheet_NAME+Sheet_row
recentID = ps.get_ss(SPREADSHEET_ID,RANGE_NAME,service)
recentID

          ID
1      49926
2      49929
3      49930
4      49931
5      49933
...      ...
9018  105291
9019  105298
9020  105303
9021  105314
9022  105315

[9022 rows x 1 columns]

In [43]:
#マスタの最後のID
cellnr = len(recentID)
latestID = recentID.at[cellnr, "ID"]
latestID = int(recentID['ID'][cellnr])
latestID

105315

In [24]:
tenki_candidate = tenki_candidate.query('tenki_ID >='+latestID)

       tenki_ID   アンタッチャ
10        49926  現S同意書回収
13        49929  現S同意書回収
14        49930  現S同意書回収
15        49931  現S同意書回収
17        49933  現S同意書回収
...         ...      ...
44429    105323  現S同意書回収
44435    105329  現S同意書回収
44440    105334  現S同意書回収
44441    105335  現S同意書回収
44442    105336  現S同意書回収

[9028 rows x 2 columns]

In [44]:
# In[8]:
tenki_untouch = tenki_candidate[['tenki_ID','アンタッチャ','変換CompanyName']].values.tolist()
tenki_untouch

[[49926, '現S同意書回収', '歯愛ﾒﾃﾞｨｶﾙ'],
 [49929, '現S同意書回収', 'LIXIL'],
 [49930, '現S同意書回収', 'なし'],
 [49931, '現S同意書回収', '大京'],
 [49933, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [49951, '現S同意書回収', 'ﾏﾂﾀﾞ'],
 [49955, '現S同意書回収', '博報堂'],
 [49957, '現S同意書回収', 'ﾐﾛｸ情報ｻｰﾋﾞｽ'],
 [49964, '現S同意書回収', 'ｷｰｴﾝｽ'],
 [49970, '現S同意書回収', 'ﾈｵｷｬﾘｱ'],
 [49974, '現S同意書回収', '富士薬品'],
 [49979, '現S同意書回収', 'TIS'],
 [49981, '現S同意書回収', '限責任あずさ監査法人'],
 [49986, '現S同意書回収', 'ｴｲｺｰ'],
 [49987, '現S同意書回収', '春'],
 [49990, '現S同意書回収', 'ﾆﾁﾚｲﾌｰｽﾞ'],
 [49993, '現S同意書回収', 'ﾃｸﾉ'],
 [49996, '現S同意書回収', 'ﾐｽﾐ'],
 [50000, '現S同意書回収', '味の素'],
 [50001, '現S同意書回収', 'ﾅｶﾞｵｶ'],
 [50003, '現S同意書回収', 'KNDｺｰﾎﾟﾚｰｼｮﾝ'],
 [50014, '現S同意書回収', 'ﾊﾟｲｵﾆｱ'],
 [50016, '現S同意書回収', 'ｵｰｹｰ'],
 [50019, '現S同意書回収', 'ﾎｰﾌﾟ'],
 [50032, '現S同意書回収', '加藤製作所'],
 [50034, '現S同意書回収', '文英堂'],
 [50037, '現S同意書回収', 'CITICCapitalPartners'],
 [50050, '現S同意書回収', '住友不動産'],
 [50058, '現S同意書回収', 'ﾗｲｵﾝ'],
 [50059, '現S同意書回収', 'ｼｰｼｰｴｽ'],
 [50061, '現S同意書回収', 'ﾒｯｸｲﾝﾀｰﾅｼｮﾅﾙ'],
 [50063, '現S同意書回収', 'なし'],
 [50065, '現S同意書回収', 'ﾔﾏｻ醤油'],
 [50067, '現S同意書回収', '鈴与工業'],
 [50068, '現S同意書回収', 'ﾆｯｼﾝｺｰﾎﾟﾚｰｼｮﾝ'],
 [50074, '現S同意書回収', 'ﾍﾞﾋﾞｰﾛｯｸ'],
 [50076, '現S同意書回収', '小林製薬'],
 [50082, '現S同意書回収', 'ﾏﾙﾌｸ電気'],
 [50085, '現S同意書回収', 'ｼﾞｪｯｸ'],
 [50096, '現S同意書回収', '大和ﾊｳｽ工業'],
 [50106, '現S同意書回収', 'LASSIC'],
 [50128, '現S同意書回収', '三幸製菓'],
 [50130, '現S同意書回収', 'ｽﾀｰｸ'],
 [50131, '現S同意書回収', '三井物産'],
 [50132, '現S同意書回収', 'いまでや'],
 [50148, '現S同意書回収', 'なし'],
 [50150, '現S同意書回収', '大和ﾊｳｽ工業'],
 [50152, '現S同意書回収', '医療法人好縁会'],
 [50156, '現S同意書回収', 'ﾘｸﾙｰﾄｺﾐｭﾆｹｰｼｮﾝｽﾞ'],
 [50157, '現S同意書回収', 'ﾈｵｷｬﾘｱ'],
 [50166, '現S同意書回収', '三井住友建設'],
 [50168, '現S同意書回収', 'ｺﾆｶﾐﾉﾙﾀ'],
 [50178, '現S同意書回収', '柿安本店'],
 [50179, '現S同意書回収', '富士ﾌｲﾙﾑ'],
 [50192, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [50201, '現S同意書回収', 'ﾃｲｴﾑ技建'],
 [50212, '現S同意書回収', 'ｴｽﾈｯﾄﾜｰｸｽ'],
 [50224, '現S同意書回収', 'ｱｸｼｽ'],
 [50226, '現S同意書回収', 'ｱｳﾃﾞｨｼﾞｬﾊﾟﾝ'],
 [50229, '現S同意書回収', '京阪ﾊﾞｽ'],
 [50239, '現S同意書回収', 'ｼﾏﾉ'],
 [50243, '現S同意書回収', 'ｵｰﾄﾋﾞｼﾞﾈｽｻｰﾋﾞｽ'],
 [50244, '現S同意書回収', 'ｴｰﾜﾝ'],
 [50254, '現S同意書回収', 'ｲﾏｽ'],
 [50258, '現S同意書回収', '個人'],
 [50259, '現S同意書回収', '東急不動産'],
 [50269, '現S同意書回収', '麦'],
 [50271, '現S同意書回収', 'ﾘｸﾙｰﾄ'],
 [50275, '現S同意書回収', 'ﾖｺｵ'],
 [50280, '現S同意書回収', 'ｲｵｽｺｰﾎﾟﾚｰｼｮﾝ'],
 [50283, '現S同意書回収', 'ｼｰﾋﾞｰｱｰﾙｲｰ'],
 [50288, '現S同意書回収', 'ｾﾙﾑ'],
 [50290, '現S同意書回収', 'ｾｷｽｲﾊｲﾑ不動産'],
 [50292, '現S同意書回収', 'ﾊﾌﾞ'],
 [50293, '現S同意書回収', '共立製薬'],
 [50306, '現S同意書回収', '大賀薬局'],
 [50316, '現S同意書回収', '山田ｺﾝｻﾙﾃｨﾝｸﾞｸﾞﾙｰﾌﾟ'],
 [50323, '現S同意書回収', 'ｽｷﾞﾉﾏｼﾝ'],
 [50324, '現S同意書回収', '岡田工業'],
 [50329, '現S同意書回収', 'ｻﾝﾄﾞ'],
 [50334, '現S同意書回収', 'ﾜｰﾙﾄﾞ'],
 [50335, '現S同意書回収', 'ﾄﾗﾝｺﾑ'],
 [50341, '現S同意書回収', 'LIXIL'],
 [50346, '現S同意書回収', 'ﾌｨｰﾙ'],
 [50348, '現S同意書回収', 'ｱｵｲ'],
 [50351, '現S同意書回収', '協成'],
 [50359, '現S同意書回収', '住友理工'],
 [50361, '現S同意書回収', 'ﾗｲﾌ住宅販売'],
 [50371, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [50374, '現S同意書回収', '光通信'],
 [50376, '現S同意書回収', 'NEC'],
 [50377, '現S同意書回収', 'NEC'],
 [50380, '現S同意書回収', 'ﾄﾗﾝｺﾑ'],
 [50393, '現S同意書回収', 'NTTﾃﾞｰﾀ'],
 [50394, '現S同意書回収', 'ﾌｧﾐﾘｱ'],
 [50403, '現S同意書回収', '日本製紙'],
 [50415, '現S同意書回収', '丸文'],
 [50418, '現S同意書回収', '代行'],
 [50421, '現S同意書回収', 'AIG損害保険'],
 [50422, '現S同意書回収', 'ﾘｱﾗｲｽﾞ'],
 [50429, '現S同意書回収', 'RPAﾃｸﾉﾛｼﾞｰｽﾞ'],
 [50430, '現S同意書回収', 'ﾔﾅｾ'],
 [50435, '現S同意書回収', ''],
 [50443, '現S同意書回収', 'UDﾄﾗｯｸｽ'],
 [50447, '現S同意書回収', 'ｵｽｶｰﾃｸﾉﾛｼﾞｰ'],
 [50449, '現S同意書回収', 'ﾋﾞｰﾎﾞ'],
 [50459, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [50463, '現S同意書回収', 'LEOC'],
 [50470, '現S同意書回収', '大黒天物産'],
 [50471, '現S同意書回収', '名古屋食糧'],
 [50482, '現S同意書回収', 'なし'],
 [50483, '現S同意書回収', 'ｱﾙﾐﾈ'],
 [50485, '現S同意書回収', 'arm'],
 [50500, '現S同意書回収', 'ｻｯﾎﾟﾛﾗｲｵﾝ'],
 [50501, '現S同意書回収', 'ｸﾛｽｺ'],
 [50506, '現S同意書回収', '戸田建設'],
 [50508, '現S同意書回収', 'SCSK'],
 [50509, '現S同意書回収', '富士通'],
 [50511, '現S同意書回収', '中村屋'],
 [50514, '現S同意書回収', 'ｷｰｴﾝｽ'],
 [50519, '現S同意書回収', 'ﾍﾞｰｽﾒﾝﾄﾌｧｸﾄﾘｰﾌﾟﾛﾀﾞｸｼｮﾝ'],
 [50522, '現S同意書回収', 'ｼﾞｪｲｴｲｼｰﾘｸﾙｰﾄﾒﾝﾄ'],
 [50523, '現S同意書回収', '湘栄建設'],
 [50524, '現S同意書回収', '三菱電機'],
 [50525, '現S同意書回収', 'ｿﾆｰ'],
 [50528, '現S同意書回収', '日本薬業'],
 [50546, '現S同意書回収', 'ｽﾘｰｺｰﾙ'],
 [50551, '現S同意書回収', 'ﾌﾛｰﾊﾞﾙ'],
 [50556, '現S同意書回収', 'ﾄﾖﾀﾚﾝﾀﾘｰｽ大阪'],
 [50558, '現S同意書回収', 'ﾔﾅｾ'],
 [50560, '現S同意書回収', 'ｱｳﾄｿｰｼﾝｸﾞﾄｰﾀﾙｻﾎﾟｰﾄ'],
 [50562, '現S同意書回収', '大和'],
 [50573, '現S同意書回収', 'EPARK'],
 [50579, '現S同意書回収', 'YCPSolidiance'],
 [50584, '現S同意書回収', 'JTB'],
 [50589, '現S同意書回収', 'ｱﾏﾉ'],
 [50593, '現S同意書回収', 'ﾌﾟﾙﾃﾞﾝｼｬﾙ生命保険'],
 [50600, '現S同意書回収', '大阪ｶﾞｽ'],
 [50602, '現S同意書回収', '日本電産ﾓﾋﾞﾘﾃｨ'],
 [50604, '現S同意書回収', 'ｼｰﾎﾞﾝ'],
 [50615, '現S同意書回収', 'ｱｸｱｲｸﾞﾆｽ'],
 [50622, '現S同意書回収', '岩田産業'],
 [50623, '現S同意書回収', '新日本空調'],
 [50635, '現S同意書回収', 'LIXIL'],
 [50641, '現S同意書回収', 'ﾗﾝｸｱｯﾌﾟ'],
 [50655, '現S同意書回収', 'ｱﾙﾊﾞｲﾄ'],
 [50661, '現S同意書回収', '池田泉州銀行'],
 [50665, '現S同意書回収', 'ﾒﾆｺﾝ'],
 [50684, '現S同意書回収', 'LINE'],
 [50689, '現S同意書回収', 'JVCｹﾝｳｯﾄﾞ'],
 [50699, '現S同意書回収', 'ﾘﾝｸ'],
 [50704, '現S同意書回収', 'ｴﾘｱﾘﾝｸ'],
 [50705, '現S同意書回収', '夢真ﾎｰﾙﾃﾞｨﾝｸﾞｽ'],
 [50714, '現S同意書回収', 'ﾊｳｽﾄﾞｩ'],
 [50717, '現S同意書回収', 'ｷﾔﾉﾝ'],
 [50722, '現S同意書回収', 'ﾌﾟﾚﾐｱｱﾝﾁｴｲｼﾞﾝｸﾞ'],
 [50725, '現S同意書回収', '岩下'],
 [50726, '現S同意書回収', 'TIS'],
 [50727, '現S同意書回収', '野村建設工業'],
 [50729, '現S同意書回収', '山下ｺﾞﾑ'],
 [50750, '現S同意書回収', 'ｾﾞﾝｼｮｰﾎｰﾙﾃﾞｨﾝｸﾞｽ'],
 [50752, '現S同意書回収', 'ｸﾘｰﾝﾃｯｸ'],
 [50753, '現S同意書回収', 'ぽぽ'],
 [50758, '現S同意書回収', 'ﾒﾋﾞｳｽ'],
 [50762, '現S同意書回収', 'ﾃﾚﾈｯﾄ'],
 [50764, '現S同意書回収', '赤福'],
 [50771, '現S同意書回収', '日産自動車'],
 [50778, '現S同意書回収', 'ﾌﾗｯﾄ'],
 [50782, '現S同意書回収', 'ﾘｺｰ'],
 [50788, '現S同意書回収', 'ｱｰｸﾚｲ'],
 [50795, '現S同意書回収', '栄進'],
 [50800, '現S同意書回収', 'ﾗｲﾌﾌﾟﾗｻﾞﾊﾟｰﾄﾅｰｽﾞ'],
 [50806, '現S同意書回収', '新生ﾎｰﾑｻｰﾋﾞｽ'],
 [50809, '現S同意書回収', 'ｸﾚｵ'],
 [50810, '現S同意書回収', '東北新社'],
 [50819, '現S同意書回収', '浜友商事'],
 [50829, '現S同意書回収', '日本郵船'],
 [50849, '現S同意書回収', 'きくや美粧堂'],
 [50858, '現S同意書回収', '三井物産'],
 [50879, '現S同意書回収', 'ﾌﾟﾚｼｬｽ'],
 [50889, '現S同意書回収', 'ｲﾝﾊﾟｸﾄ'],
 [50890, '現S同意書回収', '楽天'],
 [50894, '現S同意書回収', 'ｿﾗｽﾄ'],
 [50898, '現S同意書回収', 'CONNEXXSYSTEMS'],
 [50900, '現S同意書回収', 'LIXIL'],
 [50904, '現S同意書回収', '日本土地建物'],
 [50907, '現S同意書回収', '小野薬品工業'],
 [50908, '現S同意書回収', 'なし'],
 [50917, '現S同意書回収', 'ﾋﾟｯｸﾙｽｺｰﾎﾟﾚｰｼｮﾝ関西'],
 [50919, '現S同意書回収', 'ｷﾔﾉﾝ'],
 [50921, '現S同意書回収', '三菱ｹﾐｶﾙ'],
 [50924, '現S同意書回収', 'ﾋﾞｯﾄ'],
 [50925, '現S同意書回収', 'ﾌｫｰｻｲﾄﾞ'],
 [50930, '現S同意書回収', '岩谷産業'],
 [50932, '現S同意書回収', '生和ｱﾒﾆﾃｨ'],
 [50934, '現S同意書回収', '小林土木緑化'],
 [50941, '現S同意書回収', 'PIMﾊﾟｰﾄﾅｰｽﾞ'],
 [50942, '現S同意書回収', 'ﾄﾞｰﾑ'],
 [50944, '現S同意書回収', '太田油脂'],
 [50950, '現S同意書回収', 'なし'],
 [50957, '現S同意書回収', 'ｽｽﾞｷ'],
 [50964, '現S同意書回収', 'JM'],
 [50966, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [50972, '現S同意書回収', 'いすゞ自動車'],
 [50976, '現S同意書回収', 'ﾐｽﾞﾉ'],
 [50977, '現S同意書回収', '田食品'],
 [50980, '現S同意書回収', '丸紅'],
 [50990, '現S同意書回収', 'ﾆｺﾝ'],
 [50996, '現S同意書回収', 'ﾔﾏｼﾀ'],
 [51004, '現S同意書回収', 'JTB'],
 [51006, '現S同意書回収', '二幸産業'],
 [51013, '現S同意書回収', 'ﾐﾂﾜ'],
 [51015, '現S同意書回収', '大東建託'],
 [51018, '現S同意書回収', 'なし'],
 [51021, '現S同意書回収', 'ABC'],
 [51042, '現S同意書回収', 'ﾚｰｻﾑ'],
 [51050, '現S同意書回収', '浜友商事'],
 [51057, '現S同意書回収', 'ﾔﾏｸﾞﾁﾚｯｶｰ'],
 [51058, '現S同意書回収', '東京ｶﾞｽ'],
 [51059, '現S同意書回収', 'ｾﾗｳﾞｨﾘｿﾞｰﾄ泉郷'],
 [51064, '現S同意書回収', 'ﾈｲﾌﾞﾚｲﾝ'],
 [51067, '現S同意書回収', '共立製薬'],
 [51076, '現S同意書回収', '東日本電信電話'],
 [51077, '現S同意書回収', '光通信'],
 [51097, '現S同意書回収', '日本電信電話'],
 [51115, '現S同意書回収', '丸紅'],
 [51125, '現S同意書回収', '三菱ｹﾐｶﾙ'],
 [51128, '現S同意書回収', 'なし'],
 [51144, '現S同意書回収', '日本たばこ産業'],
 [51155, '現S同意書回収', 'ｳｨﾙｳｪｲ'],
 [51160, '現S同意書回収', 'ﾘｰﾃｲﾙﾌﾞﾗﾝﾃﾞｨﾝｸﾞ'],
 [51161, '現S同意書回収', '鈴与'],
 [51162, '現S同意書回収', 'ｹﾞｲﾄ'],
 [51169, '現S同意書回収', 'なし'],
 [51181, '現S同意書回収', 'IHI'],
 [51187, '現S同意書回収', '三菱電機'],
 [51188, '現S同意書回収', '小林香料'],
 [51190, '現S同意書回収', 'ﾕﾆﾊﾞｰｽ'],
 [51191, '現S同意書回収', '共立製薬'],
 [51205, '現S同意書回収', 'ﾔﾏﾋﾛ'],
 [51209, '現S同意書回収', 'ﾛｰﾑ'],
 [51214, '現S同意書回収', 'ﾆｺﾝ'],
 [51216, '現S同意書回収', '環境ｽﾍﾟｰｽ'],
 [51222, '現S同意書回収', '双日'],
 [51225, '現S同意書回収', '日本NCR'],
 [51226, '現S同意書回収', 'ｻﾝﾙｰﾄ'],
 [51230, '現S同意書回収', 'ｺﾆｶﾐﾉﾙﾀ'],
 [51232, '現S同意書回収', 'T-LIFEﾎｰﾙﾃﾞｨﾝｸﾞｽ'],
 [51243, '現S同意書回収', 'ｱｼｽﾄ'],
 [51256, '現S同意書回収', '木村建設'],
 [51264, '現S同意書回収', 'ﾂﾑﾗ'],
 [51266, '現S同意書回収', '社会福祉法人松風会'],
 [51271, '現S同意書回収', '三菱電機'],
 [51280, '現S同意書回収', 'ｷﾔﾉﾝ'],
 [51282, '現S同意書回収', 'bitFlyer'],
 [51286, '現S同意書回収', 'ｼﾁｽﾞﾝ電子'],
 [51287, '現S同意書回収', '丸紅'],
 [51289, '現S同意書回収', 'ｺﾆｶﾐﾉﾙﾀﾌﾟﾗﾈﾀﾘｳﾑ'],
 [51293, '現S同意書回収', 'ﾀﾙﾎﾞｯﾄｼﾞｬﾊﾟﾝ'],
 [51295, '現S同意書回収', '鈴木'],
 [51314, '現S同意書回収', '豊田通商'],
 [51324, '現S同意書回収', 'ﾘｰﾄﾞ'],
 [51325, '現S同意書回収', 'ｲﾝﾌｫｾｯｸ'],
 [51336, '現S同意書回収', 'ｽﾀｯﾌｻｰﾋﾞｽ'],
 [51341, '現S同意書回収', 'ｺﾑﾈｯﾄ'],
 [51351, '現S同意書回収', '三菱商事'],
 [51354, '現S同意書回収', 'SBI証券'],
 [51374, '現S同意書回収', '楽天ｶｰﾄﾞ'],
 [51379, '現S同意書回収', 'なし'],
 [51382, '現S同意書回収', '富士通'],
 [51383, '現S同意書回収', 'ﾋﾟｰｴｽｼｰ'],
 [51395, '現S同意書回収', 'ｼﾞｪﾑｺ日本経営'],
 [51405, '現S同意書回収', 'ﾄｩｲﾝｸﾙﾜｰﾙﾄﾞ'],
 [51407, '現S同意書回収', 'ｱﾌﾗｯｸ生命保険'],
 [51413, '現S同意書回収', '横田'],
 [51414, '現S同意書回収', '博報堂'],
 [51420, '現S同意書回収', '博報堂'],
 [51423, '現S同意書回収', '味の素'],
 [51438, '現S同意書回収', '一蔵'],
 [51444, '現S同意書回収', 'Repro'],
 [51446, '現S同意書回収', 'RIZAPｸﾞﾙｰﾌﾟ'],
 [51450, '現S同意書回収', 'DTS'],
 [51455, '現S同意書回収', 'ﾃﾞｨﾗｲﾄ'],
 [51462, '現S同意書回収', 'ｵﾒｶﾞﾃｸﾉ'],
 [51463, '現S同意書回収', '日本交通'],
 [51470, '現S同意書回収', 'ｴｲﾌﾞﾙ'],
 [51477, '現S同意書回収', '電通'],
 [51484, '現S同意書回収', '松本興産'],
 [51487, '現S同意書回収', 'ｷﾔﾉﾝ'],
 [51490, '現S同意書回収', 'ﾅｶﾞｾ'],
 [51492, '現S同意書回収', '東京ﾌｰﾄﾞ'],
 [51494, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [51497, '現S同意書回収', 'ﾄﾖﾀｱﾒﾆﾃｨ'],
 [51507, '現S同意書回収', 'ﾌﾞﾘｯｸｽ'],
 [51508, '現S同意書回収', 'BEENOS'],
 [51509, '現S同意書回収', 'ﾎﾝﾀﾞ運送'],
 [51515, '現S同意書回収', '電通'],
 [51525, '現S同意書回収', '栄光'],
 [51527, '現S同意書回収', '日本電気'],
 [51530, '現S同意書回収', 'ﾅｯﾌﾟ'],
 [51532, '現S同意書回収', '若林'],
 [51533, '現S同意書回収', 'ﾀﾞｲｴｰ'],
 [51536, '現S同意書回収', 'ｸﾞﾗﾝﾃ'],
 [51538, '現S同意書回収', 'TSUTAYA'],
 [51547, '現S同意書回収', '御前崎海運'],
 [51550, '現S同意書回収', '電通'],
 [51553, '現S同意書回収', 'ﾘﾌﾟﾛﾗｲﾌ'],
 [51564, '現S同意書回収', 'ｵｽﾞ'],
 [51566, '現S同意書回収', '岡田工業'],
 [51573, '現S同意書回収', '味の素'],
 [51584, '現S同意書回収', 'ｿﾆｰ'],
 [51588, '現S同意書回収', 'ﾊﾟﾙｺ'],
 [51590, '現S同意書回収', 'BAKE'],
 [51592, '現S同意書回収', '興建'],
 [51594, '現S同意書回収', 'ｹｱｻﾎﾟｰﾄ'],
 [51601, '現S同意書回収', 'ｻﾝｷｭｰﾄﾞﾗｯｸﾞ'],
 [51605, '現S同意書回収', 'JTB'],
 [51606, '現S同意書回収', 'ｺｰﾌｸ'],
 [51612, '現S同意書回収', '日本ｱｸｾｽ'],
 [51615, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [51630, '現S同意書回収', '浪速運送'],
 [51634, '現S同意書回収', 'ｱｲｿﾆｰﾌｰｽﾞ'],
 [51637, '現S同意書回収', ''],
 [51641, '現S同意書回収', '府中ﾌﾟﾗ'],
 [51643, '現S同意書回収', '電通'],
 [51650, '現S同意書回収', 'ｿﾆｰ'],
 [51651, '現S同意書回収', 'ﾏﾂﾀﾞ'],
 [51655, '現S同意書回収', 'ﾌｸｼﾏｶﾞﾘﾚｲ'],
 [51672, '現S同意書回収', 'ﾄｰﾎｰ'],
 [51675, '現S同意書回収', '三井物産'],
 [51678, '現S同意書回収', 'TDK'],
 [51681, '現S同意書回収', 'ｸﾞｯﾄﾞﾗｲﾌ'],
 [51682, '現S同意書回収', 'ﾆｭｰｽﾞﾍﾞｰｽ'],
 [51685, '現S同意書回収', ''],
 [51691, '現S同意書回収', 'ﾒﾃﾞｨｵﾃｯｸ'],
 [51694, '現S同意書回収', 'ﾊﾞﾛｰﾎｰﾙﾃﾞｨﾝｸﾞｽ'],
 [51697, '現S同意書回収', 'ｲｵﾝﾘﾃｰﾙ'],
 [51700, '現S同意書回収', 'ﾎﾜｲﾄﾊｳｽ'],
 [51707, '現S同意書回収', 'ﾌｶｼ'],
 [51711, '現S同意書回収', 'ﾊﾞﾙ'],
 [51713, '現S同意書回収', 'なし'],
 [51714, '現S同意書回収', '三井物産ﾌｫｰｻｲﾄ'],
 [51715, '現S同意書回収', '東日本電信電話'],
 [51723, '現S同意書回収', 'ｶﾜｲ'],
 [51730, '現S同意書回収', 'ﾘｸﾙｰﾄR&Dｽﾀｯﾌｨﾝｸﾞ'],
 [51741, '現S同意書回収', '櫻製作所'],
 [51743, '現S同意書回収', 'ﾚｼﾞﾃﾞﾝｽ'],
 [51760, '現S同意書回収', 'ｵﾘｯｸｽ'],
 [51765, '現S同意書回収', 'ｿﾆｰ'],
 [51782, '現S同意書回収', 'ｲｵﾝﾃﾞｨﾗｲﾄ'],
 [51789, '現S同意書回収', '三井物産'],
 [51791, '現S同意書回収', '電通'],
 [51793, '現S同意書回収', '東洋電装'],
 [51796, '現S同意書回収', 'RiseUP'],
 [51799, '現S同意書回収', '広島銀行'],
 [51805, '現S同意書回収', '東通ｲﾝﾃｸﾞﾚｰﾄ'],
 [51807, '現S同意書回収', 'ﾛｰﾗﾝﾄﾞ'],
 [51809, '現S同意書回収', 'ｱﾄﾑ'],
 [51812, '現S同意書回収', '拓匠開発'],
 [51818, '現S同意書回収', 'ｼﾙﾊﾞｰﾊﾞｯｸ'],
 [51821, '現S同意書回収', 'ﾄｰｺｰ'],
 [51822, '現S同意書回収', 'ｻﾝｾｯﾄｺｰﾎﾟﾚｲｼｮﾝ'],
 [51825, '現S同意書回収', 'MOTA'],
 [51829, '現S同意書回収', 'ｼﾞｪﾈﾗﾙｻｰﾋﾞｼｰｽﾞ'],
 [51837, '現S同意書回収', '日本電気'],
 [51855, '現S同意書回収', 'ｱﾝﾋﾞｼｮﾝ'],
 [51875, '現S同意書回収', 'ｽﾜﾝ'],
 [51881, '現S同意書回収', 'ｻﾝﾕｰ都市開発'],
 [51896, '現S同意書回収', 'ﾉｰﾌﾞﾙ'],
 [51899, '現S同意書回収', 'ｲﾝﾃﾘｯｸｽ'],
 [51903, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [51905, '現S同意書回収', '日本ｺﾝｻﾙﾀﾝﾂ'],
 [51910, '現S同意書回収', 'なし'],
 [51917, '現S同意書回収', 'Kｸﾘｴｲﾄ'],
 [51925, '現S同意書回収', '三井物産'],
 [51926, '現S同意書回収', 'ﾛｰﾗｱｼｭﾚｲｼﾞｬﾊﾟﾝ'],
 [51931, '現S同意書回収', 'ﾄｰｷﾝ'],
 [51936, '現S同意書回収', '全日警'],
 [51937, '現S同意書回収', 'ﾃｰｵｰ食品'],
 [51953, '現S同意書回収', 'TMJ'],
 [51963, '現S同意書回収', 'TMJ'],
 [51965, '現S同意書回収', 'E-BONDﾎｰﾙﾃﾞｨﾝｸﾞｽ'],
 [51969, '現S同意書回収', '京伸'],
 [51985, '現S同意書回収', '日立産業制御ｿﾘｭｰｼｮﾝｽﾞ'],
 [51986, '現S同意書回収', 'ｼﾞﾌﾞﾗﾙﾀ生命保険'],
 [51987, '現S同意書回収', '富士通'],
 [51988, '現S同意書回収', '菱神'],
 [51989, '現S同意書回収', 'TOWA'],
 [51990, '現S同意書回収', 'ﾘﾛｸﾗﾌﾞ'],
 [51992, '現S同意書回収', 'ｼﾋﾞﾙ'],
 [51999, '現S同意書回収', 'ｱﾝﾘﾂ'],
 [52000, '現S同意書回収', 'ﾀﾞｲﾅｯｸｽ'],
 [52011, '現S同意書回収', 'NAITO'],
 [52015, '現S同意書回収', '中央建設'],
 [52025, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52026, '現S同意書回収', 'ｼｰｱｲｼｰ'],
 [52034, '現S同意書回収', 'JTB'],
 [52037, '現S同意書回収', 'なし'],
 [52046, '現S同意書回収', 'ﾔﾌｰ'],
 [52051, '現S同意書回収', 'ｺﾆｶﾐﾉﾙﾀ'],
 [52053, '現S同意書回収', 'ﾋﾞｽﾞｵｰｼｬﾝ'],
 [52083, '現S同意書回収', 'ｾﾝﾄﾗﾙ'],
 [52085, '現S同意書回収', 'RIZAPｸﾞﾙｰﾌﾟ'],
 [52087, '現S同意書回収', '総合ﾒﾃﾞｨｶﾙ'],
 [52091, '現S同意書回収', 'ｾｷ'],
 [52097, '現S同意書回収', 'ｲﾝﾄﾗｽﾄ'],
 [52099, '現S同意書回収', '東京海上日動'],
 [52114, '現S同意書回収', '明光ﾈｯﾄﾜｰｸｼﾞｬﾊﾟﾝ'],
 [52115, '現S同意書回収', '中央ｱｲﾃﾞﾝ'],
 [52117, '現S同意書回収', '電通'],
 [52123, '現S同意書回収', '岡田工業'],
 [52142, '現S同意書回収', 'GE'],
 [52143, '現S同意書回収', '総合警備保障'],
 [52155, '現S同意書回収', '住友不動産'],
 [52157, '現S同意書回収', '武蔵野銀行'],
 [52160, '現S同意書回収', 'ﾍﾞｰｽ'],
 [52161, '現S同意書回収', 'ｼﾞｪﾝｻｰﾑｼﾞｬﾊﾟﾝ'],
 [52164, '現S同意書回収', 'ｱｲ工務店'],
 [52174, '現S同意書回収', '大三紙業'],
 [52185, '現S同意書回収', '味の素'],
 [52188, '現S同意書回収', '河内屋'],
 [52197, '現S同意書回収', 'SGﾎｰﾙﾃﾞｨﾝｸﾞｽ'],
 [52205, '現S同意書回収', 'ﾗｲﾌﾄﾞﾘﾝｸｶﾝﾊﾟﾆｰ'],
 [52212, '現S同意書回収', 'LINE'],
 [52213, '現S同意書回収', '日本ｼｽﾃﾑ'],
 [52219, '現S同意書回収', 'ﾌﾗｯｸﾞ'],
 [52224, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52228, '現S同意書回収', 'ｼﾞｬｽﾄ'],
 [52230, '現S同意書回収', 'なし'],
 [52247, '現S同意書回収', '世紀東急工業'],
 [52253, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52257, '現S同意書回収', 'ｱｲｻﾞｯｸ'],
 [52264, '現S同意書回収', 'ﾐﾛｸ情報ｻｰﾋﾞｽ'],
 [52272, '現S同意書回収', 'ﾌﾟﾙﾃﾞﾝｼｬﾙ生命保険'],
 [52278, '現S同意書回収', '味の素'],
 [52283, '現S同意書回収', 'ｳｲﾝｸﾞ'],
 [52292, '現S同意書回収', '極東ﾘｰｽ'],
 [52293, '現S同意書回収', 'ｺﾝｼｪﾙｼﾞｭ'],
 [52298, '現S同意書回収', 'ﾋﾞﾃﾞｵﾌﾟﾛﾓｰｼｮﾝ'],
 [52299, '現S同意書回収', 'ｼｰｽﾞﾝ'],
 [52303, '現S同意書回収', '日本ﾏｸﾄﾞﾅﾙﾄﾞ'],
 [52314, '現S同意書回収', '栃木屋'],
 [52315, '現S同意書回収', 'ｺﾆｶﾐﾉﾙﾀ'],
 [52320, '現S同意書回収', 'はるやま商事'],
 [52324, '現S同意書回収', 'ｶﾞｰﾃﾞﾝ'],
 [52327, '現S同意書回収', 'ｳｨｻﾞｽ'],
 [52331, '現S同意書回収', 'ﾄｰｼｮｰ'],
 [52334, '現S同意書回収', 'BrandingEngineer'],
 [52337, '現S同意書回収', '三菱ｹﾐｶﾙ'],
 [52338, '現S同意書回収', '三井化学'],
 [52339, '現S同意書回収', 'AIG損害保険'],
 [52340, '現S同意書回収', 'ｲｵﾝﾌｧﾝﾀｼﾞｰ'],
 [52350, '現S同意書回収', '個人'],
 [52352, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52353, '現S同意書回収', '楽天'],
 [52363, '現S同意書回収', '住友生命保険相互会社'],
 [52366, '現S同意書回収', '日産自動車'],
 [52369, '現S同意書回収', '大興ﾈｸｽﾀ'],
 [52381, '現S同意書回収', '三友'],
 [52386, '現S同意書回収', 'ｽﾀｼﾞｵｱｲ'],
 [52388, '現S同意書回収', 'SBSﾌﾚｲﾄｻｰﾋﾞｽ'],
 [52391, '現S同意書回収', 'ﾄﾖﾀ自動車'],
 [52399, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52401, '現S同意書回収', 'LINE'],
 [52404, '現S同意書回収', 'ﾀﾋﾞｯｸｽｼﾞｬﾊﾟﾝ'],
 [52405, '現S同意書回収', '飯塚製作所'],
 [52406, '現S同意書回収', 'ﾏｷﾀ'],
 [52407, '現S同意書回収', '兼松'],
 [52410, '現S同意書回収', 'ﾐｴｽﾚｰﾄ'],
 [52414, '現S同意書回収', 'ﾐｽﾐｸﾞﾙｰﾌﾟ本社'],
 [52420, '現S同意書回収', 'NTS'],
 [52421, '現S同意書回収', 'ｻﾗﾔ'],
 [52424, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52428, '現S同意書回収', 'ﾕﾆﾊﾞｰｻﾙ'],
 [52434, '現S同意書回収', '夢真'],
 [52436, '現S同意書回収', '博報堂'],
 [52437, '現S同意書回収', '博報堂'],
 [52438, '現S同意書回収', 'ｱﾏﾉ'],
 [52439, '現S同意書回収', 'ﾉｰﾌﾞﾙﾎｰﾑ'],
 [52442, '現S同意書回収', 'ﾘｸﾙｰﾄｷｬﾘｱ'],
 [52444, '現S同意書回収', '博報堂'],
 [52446, '現S同意書回収', '社会福祉法人'],
 [52449, '現S同意書回収', '博報堂'],
 [52451, '現S同意書回収', 'ｶｰﾌﾞｽﾎｰﾙﾃﾞｨﾝｸﾞｽ'],
 [52454, '現S同意書回収', 'ﾘｺｰ'],
 [52455, '現S同意書回収', 'ｵﾑﾛﾝ'],
 [52460, '現S同意書回収', 'LEAR'],
 [52469, '現S同意書回収', 'ﾏﾙﾌｸ'],
 [52473, '現S同意書回収', 'ﾄﾖﾀ自動車'],
 [52479, '現S同意書回収', '富士通'],
 [52482, '現S同意書回収', 'ﾄﾖﾀ自動車'],
 [52484, '現S同意書回収', 'ﾌｧｲﾌﾞｸﾞﾙｰﾌﾟ'],
 [52497, '現S同意書回収', 'ｿﾐｯｸ石川'],
 [52503, '現S同意書回収', 'RIZAPｸﾞﾙｰﾌﾟ'],
 [52505, '現S同意書回収', 'ｸｰﾘｴ'],
 [52506, '現S同意書回収', '三菱商事'],
 [52513, '現S同意書回収', 'ﾋﾞｵﾒﾃﾞｨｸｽ'],
 [52519, '現S同意書回収', '神栄'],
 [52524, '現S同意書回収', '三菱商事'],
 [52525, '現S同意書回収', ''],
 [52529, '現S同意書回収', 'ｽｸﾙﾄﾞｱﾝﾄﾞｶﾝﾊﾟﾆｰ'],
 [52531, '現S同意書回収', 'ﾘﾋﾞﾝｸﾞﾗｲﾌ'],
 [52532, '現S同意書回収', 'ﾃﾞｼﾞﾀﾙｱｰﾂ'],
 [52534, '現S同意書回収', '木村'],
 [52537, '現S同意書回収', 'ﾃﾞﾝｿｰ'],
 [52540, '現S同意書回収', 'ｺﾆｶﾐﾉﾙﾀ'],
 [52542, '現S同意書回収', 'ｷｰｴﾝｽ'],
 [52546, '現S同意書回収', 'ｹｱｻｰﾋﾞｽ'],
 [52547, '現S同意書回収', '日産自動車'],
 [52548, '現S同意書回収', '滋賀銀行'],
 [52555, '現S同意書回収', 'JVCｹﾝｳｯﾄﾞ'],
 [52587, '現S同意書回収', 'UDﾄﾗｯｸｽ'],
 [52596, '現S同意書回収', '三菱商事'],
 [52606, '現S同意書回収', '三菱商事'],
 [52607, '現S同意書回収', 'ｵﾑﾛﾝ'],
 [52614, '現S同意書回収', '青木'],
 [52615, '現S同意書回収', '大運'],
 [52619, '現S同意書回収', '千代田化工建設'],
 [52625, '現S同意書回収', 'ﾛﾝ'],
 [52626, '現S同意書回収', 'ｸｵﾘﾃｨｰ'],
 [52631, '現S同意書回収', 'ﾌﾞﾛｰﾄﾞﾘｰﾌ'],
 [52633, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52637, '現S同意書回収', '医療法人'],
 [52638, '現S同意書回収', 'ｱﾄﾐｯｸ'],
 [52639, '現S同意書回収', 'ﾌﾟﾙﾃﾞﾝｼｬﾙ生命保険'],
 [52645, '現S同意書回収', 'TIS'],
 [52646, '現S同意書回収', 'ｱﾙﾌｧｸﾗﾌﾞ武蔵野'],
 [52649, '現S同意書回収', 'ｸﾞﾛｰﾊﾞﾙ'],
 [52652, '現S同意書回収', '東洋電産'],
 [52675, '現S同意書回収', 'ｿﾆｰ'],
 [52684, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52685, '現S同意書回収', 'ｽﾀｲﾙ'],
 [52690, '現S同意書回収', '博報堂'],
 [52697, '現S同意書回収', 'ｱﾄﾞｳﾞｧﾝｽｱｰｷﾃｸﾂ'],
 [52721, '現S同意書回収', 'ﾌﾞﾘﾁﾞｽﾄﾝ'],
 [52723, '現S同意書回収', 'ｶﾙﾋﾞｰ'],
 [52726, '現S同意書回収', '双日'],
 [52728, '現S同意書回収', 'ﾀﾞｲﾅｯｸｽ'],
 [52733, '現S同意書回収', 'ｳｴﾆ貿易'],
 [52743, '現S同意書回収', 'ﾃｲｼﾞｲｴﾙ'],
 [52745, '現S同意書回収', '上野商会'],
 [52748, '現S同意書回収', 'ﾗｲｼﾞﾝｸﾞ'],
 [52750, '現S同意書回収', 'ﾘｺｰ'],
 [52762, '現S同意書回収', 'ﾔﾝﾏｰ'],
 [52768, '現S同意書回収', '味の素'],
 [52779, '現S同意書回収', 'ﾅｲﾙ'],
 [52780, '現S同意書回収', '日本住宅'],
 [52785, '現S同意書回収', 'ﾌｫｰｼｰｽﾞ'],
 [52786, '現S同意書回収', 'ﾆﾁﾘｮｸ'],
 [52789, '現S同意書回収', '一蔵'],
 [52793, '現S同意書回収', '大伸開発工業'],
 [52799, '現S同意書回収', 'ﾛｰﾑ'],
 [52800, '現S同意書回収', '大和輸送'],
 [52817, '現S同意書回収', 'ｱｽｶｴﾝｼﾞﾆｱﾘﾝｸﾞ'],
 [52821, '現S同意書回収', 'ｴｰｴﾙｼｰ'],
 [52822, '現S同意書回収', '三井物産'],
 [52829, '現S同意書回収', '大正製薬'],
 [52830, '現S同意書回収', 'ｼｵﾔ'],
 [52831, '現S同意書回収', 'ﾄｸﾔﾏ'],
 [52834, '現S同意書回収', '三菱商事'],
 [52837, '現S同意書回収', 'ｱｷﾀ'],
 [52838, '現S同意書回収', 'ｹｲｺｰﾎﾟﾚｰｼｮﾝ'],
 [52863, '現S同意書回収', 'ｻﾝﾊﾟｰｸ'],
 [52872, '現S同意書回収', '平和物産'],
 [52874, '現S同意書回収', '味の素'],
 [52876, '現S同意書回収', 'ｵｵｶ商事'],
 [52881, '現S同意書回収', '双日'],
 [52882, '現S同意書回収', '大東建託'],
 [52887, '現S同意書回収', 'LDK'],
 [52898, '現S同意書回収', '富士通'],
 [52906, '現S同意書回収', 'ｴﾑｹｰ精工'],
 [52919, '現S同意書回収', 'ﾃｨｴﾇ'],
 [52923, '現S同意書回収', ''],
 [52927, '現S同意書回収', 'ｻﾝﾄﾞﾗｯｸﾞ'],
 [52930, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [52932, '現S同意書回収', 'なし'],
 [52934, '現S同意書回収', '三菱電機'],
 [52941, '現S同意書回収', 'ﾔﾌｰ'],
 [52957, '現S同意書回収', '世紀東急工業'],
 [52973, '現S同意書回収', 'HOWA'],
 [52981, '現S同意書回収', '富士通研究所'],
 [52982, '現S同意書回収', 'M&Aｷｬﾋﾟﾀﾙﾊﾟｰﾄﾅｰｽﾞ'],
 [52983, '現S同意書回収', '和'],
 [52992, '現S同意書回収', 'ﾘｺｰｼﾞｬﾊﾟﾝ'],
 [52993, '現S同意書回収', 'ﾏﾙｲﾁ産商'],
 [53014, '現S同意書回収', '奥井組'],
 [53016, '現S同意書回収', 'ｿﾆｰ'],
 [53021, '現S同意書回収', 'ｷﾔﾉﾝ'],
 [53032, '現S同意書回収', 'ｱﾙﾌｧﾗｲﾌ'],
 [53036, '現S同意書回収', '第一医科'],
 [53042, '現S同意書回収', 'ﾒﾃﾞｨｱﾈｯﾄﾜｰｸ'],
 [53043, '現S同意書回収', 'ﾜｲｽﾞ'],
 [53048, '現S同意書回収', '緑書房'],
 [53053, '現S同意書回収', 'ﾔﾑﾔﾑｸﾘｴｲﾂ'],
 [53057, '現S同意書回収', '愛知日産自動車'],
 [53069, '現S同意書回収', '三井物産'],
 [53071, '現S同意書回収', '朝日酒造'],
 [53081, '現S同意書回収', 'ｱｸﾞﾚｯｸｽ'],
 [53086, '現S同意書回収', 'ﾗｯｸ'],
 [53111, '現S同意書回収', 'JTB'],
 [53114, '現S同意書回収', 'ﾐｻﾜﾎｰﾑ'],
 [53127, '現S同意書回収', 'ﾃﾞﾝｿｰ'],
 [53131, '現S同意書回収', 'ﾄﾞｰﾑ'],
 [53135, '現S同意書回収', '田中精密工業'],
 [53140, '現S同意書回収', 'ﾀｲｶ'],
 [53143, '現S同意書回収', 'ﾊﾟﾅｿﾆｯｸ'],
 [53147, '現S同意書回収', 'ﾋﾞｰﾌﾟﾗｽﾄ'],
 [53150, '現S同意書回収', '東洋'],
 [53158, '現S同意書回収', 'ｿﾆｰ'],
 [53161, '現S同意書回収', '京伸'],
 [53162, '現S同意書回収', '日本電気'],
 [53168, '現S同意書回収', 'ｿﾆｰ'],
 [53171, '現S同意書回収', '東秀'],
 [53177, '現S同意書回収', '西松建設'],
 [53179, '現S同意書回収', 'iXIT'],
 [53196, '現S同意書回収', 'ﾆｭｰﾄﾗﾙ'],
 [53200, '現S同意書回収', 'ﾋﾞｰｲﾝｸﾞｺﾝｻﾙﾃｨﾝｸﾞ'],
 [53207, '現S同意書回収', 'ﾄｰｱ'],
 [53210, '現S同意書回収', 'LGJapanLab'],
 [53211, '現S同意書回収', '学校法人なぎの学園'],
 [53212, '現S同意書回収', 'ﾏﾙﾎ'],
 [53216, '現S同意書回収', 'ｻﾝｴｰ'],
 [53217, '現S同意書回収', '東建ｺｰﾎﾟﾚｰｼｮﾝ'],
 [53229, '現S同意書回収', '豊田通商'],
 [53230, '現S同意書回収', '電通'],
 [53234, '現S同意書回収', 'ﾘｸﾙｰﾄR&Dｽﾀｯﾌｨﾝｸﾞ'],
 [53240, '現S同意書回収', '山田工業'],
 [53256, '現S同意書回収', 'ﾛｲﾔﾙ'],
 [53260, '現S同意書回収', '三菱ｹﾐｶﾙ'],
 [53265, '現S同意書回収', '東洋ﾋﾞｭｰﾃｨ'],
 [53267, '現S同意書回収', 'ﾀﾞｯｸｽ'],
 [53269, '現S同意書回収', 'ｼｰｸｽ'],
 [53275, '現S同意書回収', 'JET'],
 [53279, '現S同意書回収', '興和'],
 [53280, '現S同意書回収', 'なし'],
 [53283, '現S同意書回収', '日本電産'],
 [53284, '現S同意書回収', 'ﾌﾞﾚｲﾌﾞ'],
 [53286, '現S同意書回収', '東洋ﾃｯｸ'],
 [53294, '現S同意書回収', 'ﾚﾅｳﾝ'],
 [53297, '現S同意書回収', 'ｷｰｴﾝｽ'],
 [53301, '現S同意書回収', ''],
 [53308, '現S同意書回収', 'ｵﾝｱﾝﾄﾞｵﾝ'],
 [53316, '現S同意書回収', 'ｱｰﾙﾃﾞｨｰｼｰ'],
 [53321, '現S同意書回収', 'ﾅｲｶﾞｲ'],
 [53327, '現S同意書回収', 'ｿﾆｰ'],
 [53336, '現S同意書回収', 'ﾌｰﾄﾞﾘｳﾞｧﾝﾌﾟ'],
 [53340, '現S同意書回収', 'ﾓﾄﾔﾕﾅｲﾃｯﾄﾞ'],
 [53361, '現S同意書回収', '両備ｼｽﾃﾑｽﾞ'],
 [53372, '現S同意書回収', 'ｱｰﾙｱｲ'],
 [62136, '現S同意書回収', '住友不動産'],
 [62137, '現S同意書回収', 'ﾄﾞｰﾑ'],
 [62154, '現S同意書回収', 'ﾎﾟｰﾗ'],

In [45]:
###ここを編集
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly',
          'https://www.googleapis.com/auth/spreadsheets']
SPREADSHEET_ID = '15qRR-yfJxgCh_TpXwBjBHNAnc8yAeTUCF0-Y_N6GoIo'
RANGE_NAME = '現Sチェック!A2'
json_path = "credentials.json"
service = ps.get_auth(SCOPES, json_path)
ps.update_ss(SPREADSHEET_ID,RANGE_NAME,tenki_untouch,service)